### PR TITLE
Fix player 1 controls affecting others in player selection

### LINKED ISSUE #855: Player 1 controls can affect other players in character selection
The default player 1 controls (up, down, left, right), also control the menus of the second player if selected. The second player controls only affect the second player menu.

Video showing the issue:
https://www.youtube.com/watch?v=HJVdF7TUMuY

I believe the character selection menus should be tied to the individual controls of the players. On the other hand, this could be used to mess with people when playing local coop...

### PR DESCRIPTION
**Pull request by Kurtsley**
Fixes #855 

Prevents player one's controls from affecting other players in the player selection menu.

See comment:
https://github.com/cxong/cdogs-sdl/issues/855#issuecomment-2166611821

### CODE REVIEW

File: src/prep.c [hunk 1]
```diff
@@ -409,7 +409,6 @@ static GameLoopResult PlayerSelectionUpdate(GameLoopData *data, LoopRunner *l)
 
 	// Menu input
 	int idx = 0;
-	const bool useMenuCmd = GetNumPlayers(PLAYER_ANY, true, true);
```
Comment (cxong) [inline src/prep.c:412]: this should not be removed; it is to make sure default  menu commands (arrow keys) are usable in menus regardless of what player one key binds are
instead this bool should depend on whether there are multiple local non-AI players

Comment (Kurtsley) [reply src/prep.c:412]: Gotcha, I'll try another approach.

**Comment by Kurtsley** [comment]
So by checking if useMenuCmd returns more than 1 here, as per the suggestion, it essentially disables the default menu commands for all menus that have multiple players ex: equip menu. The default commands seem to work in all other menus. This functionality looks to be supported as the text at the bottom of most menus shows the default controls, but it switches to the mapped controls in the player select screen.
